spring.application.name=shipmentPackageService
logging.config=classpath:logback-observability.xml
server.port=8111
spring.jpa.hibernate.ddl-auto=update
spring.cloud.config.fail-fast=false
management.endpoints.web.exposure.include=prometheus,health,info
